# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalenderFeed',
            new_name='CalendarFeed',
        ),
    ]
